---
apiVersion: v1
kind: Namespace
metadata:
  name: game-2048
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev-coinbase-namespace 
  name: mysql
spec:
  type: ExternalName
  externalName: usermgmtdb.ckfzgtrt9mue.eu-west-2.rds.amazonaws.com