---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-coinbase-namespace
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod-coinbase-namespace 
  name: mysql
spec:
  type: ExternalName
  externalName: coinbase-database.cau9n3cvqgxd.us-east-1.rds.amazonaws.com